// Login / account pages for known services.
// These are the main entry points where users can sign in and manage their subscription.
const CANCEL_URL_MAP: Record<string, string> = {
  // Streaming video
  "netflix": "https://www.netflix.com/login",
  "hulu": "https://www.hulu.com/login",
  "disney+": "https://www.disneyplus.com/login",
  "disney plus": "https://www.disneyplus.com/login",
  "amazon prime": "https://www.amazon.com/ap/signin",
  "amazon prime video": "https://www.amazon.com/ap/signin",
  "prime video": "https://www.amazon.com/ap/signin",
  "hbo": "https://www.max.com/login",
  "hbo max": "https://www.max.com/login",
  "max": "https://www.max.com/login",
  "apple tv+": "https://appleid.apple.com",
  "apple tv plus": "https://appleid.apple.com",
  "peacock": "https://www.peacocktv.com/signin",
  "paramount+": "https://www.paramountplus.com/account/signin/",
  "paramount plus": "https://www.paramountplus.com/account/signin/",
  "youtube premium": "https://www.youtube.com/paid_memberships",
  "youtube tv": "https://tv.youtube.com/welcome/",
  "crunchyroll": "https://www.crunchyroll.com/login",
  "twitch": "https://www.twitch.tv/login",
  "discovery+": "https://www.discoveryplus.com/login",
  "discovery plus": "https://www.discoveryplus.com/login",
  "espn+": "https://www.espn.com/login",
  "espn plus": "https://www.espn.com/login",
  "mubi": "https://mubi.com/login",
  "shudder": "https://www.shudder.com/login",
  "plex": "https://app.plex.tv/auth/#/",

  // Music
  "spotify": "https://accounts.spotify.com/login",
  "apple music": "https://appleid.apple.com",
  "tidal": "https://login.tidal.com",
  "soundcloud": "https://soundcloud.com/signin",
  "pandora": "https://www.pandora.com/account/sign-in",
  "deezer": "https://www.deezer.com/login",
  "amazon music": "https://www.amazon.com/ap/signin",
  "audible": "https://www.audible.com/sign-in",
  "kindle unlimited": "https://www.amazon.com/ap/signin",

  // Productivity & SaaS
  "microsoft 365": "https://account.microsoft.com",
  "office 365": "https://account.microsoft.com",
  "microsoft office": "https://account.microsoft.com",
  "google workspace": "https://admin.google.com",
  "google one": "https://one.google.com",
  "dropbox": "https://www.dropbox.com/login",
  "notion": "https://www.notion.so/login",
  "slack": "https://slack.com/signin",
  "zoom": "https://zoom.us/signin",
  "github": "https://github.com/login",
  "github copilot": "https://github.com/login",
  "gitlab": "https://gitlab.com/users/sign_in",
  "adobe": "https://account.adobe.com",
  "adobe creative cloud": "https://account.adobe.com",
  "adobe acrobat": "https://account.adobe.com",
  "adobe acrobat pro": "https://account.adobe.com",
  "adobe acrobat reader": "https://account.adobe.com",
  "adobe photoshop": "https://account.adobe.com",
  "adobe illustrator": "https://account.adobe.com",
  "adobe premiere": "https://account.adobe.com",
  "figma": "https://www.figma.com/login",
  "linear": "https://linear.app/login",
  "jira": "https://id.atlassian.com/login",
  "confluence": "https://id.atlassian.com/login",
  "atlassian": "https://id.atlassian.com/login",
  "trello": "https://trello.com/login",
  "asana": "https://app.asana.com/-/login",
  "monday": "https://auth.monday.com/login",
  "monday.com": "https://auth.monday.com/login",
  "clickup": "https://app.clickup.com/login",
  "airtable": "https://airtable.com/login",
  "webflow": "https://webflow.com/login",
  "squarespace": "https://login.squarespace.com",
  "shopify": "https://accounts.shopify.com/login",
  "mailchimp": "https://login.mailchimp.com",
  "canva": "https://www.canva.com/login",
  "grammarly": "https://www.grammarly.com/signin",

  // Security & Privacy
  "1password": "https://my.1password.com/signin",
  "lastpass": "https://lastpass.com/login",
  "dashlane": "https://app.dashlane.com/login",
  "bitwarden": "https://vault.bitwarden.com/#/login",
  "nordvpn": "https://my.nordaccount.com/login/",
  "expressvpn": "https://www.expressvpn.com/sign-in",
  "surfshark": "https://my.surfshark.com/auth/login",
  "proton": "https://account.proton.me",
  "protonmail": "https://account.proton.me",
  "proton vpn": "https://account.proton.me",
  "protonvpn": "https://account.proton.me",

  // AI & Dev tools
  "chatgpt": "https://chat.openai.com/auth/login",
  "openai": "https://platform.openai.com/login",
  "vercel": "https://vercel.com/login",
  "netlify": "https://app.netlify.com/login",
  "digitalocean": "https://cloud.digitalocean.com/login",
  "cloudflare": "https://dash.cloudflare.com/login",
  "datadog": "https://app.datadoghq.com/account/login",

  // Food & delivery
  "hellofresh": "https://www.hellofresh.com/login",
  "hello fresh": "https://www.hellofresh.com/login",
  "factor": "https://www.factor75.com/login",
  "factor 75": "https://www.factor75.com/login",
  "green chef": "https://www.greenchef.com/login",
  "every plate": "https://www.everyplate.com/login",
  "everyplate": "https://www.everyplate.com/login",
  "home chef": "https://www.homechef.com/login",
  "marley spoon": "https://marleyspoon.com/login",
  "sun basket": "https://sunbasket.com/login",

  // Fitness & wellness
  "peloton": "https://members.onepeloton.com",
  "noom": "https://web.noom.com/login",
  "calm": "https://www.calm.com/signin",
  "headspace": "https://www.headspace.com/login",
  "strava": "https://www.strava.com/login",
  "whoop": "https://app.whoop.com/login",

  // Gaming
  "xbox game pass": "https://account.microsoft.com",
  "xbox game pass ultimate": "https://account.microsoft.com",
  "xbox": "https://account.microsoft.com",
  "playstation": "https://store.playstation.com/login",
  "playstation plus": "https://store.playstation.com/login",
  "playstation now": "https://store.playstation.com/login",
  "playstation network": "https://store.playstation.com/login",
  "sony playstation": "https://store.playstation.com/login",
  "ps plus": "https://store.playstation.com/login",
  "ps now": "https://store.playstation.com/login",
  "psn": "https://store.playstation.com/login",
  "nintendo switch online": "https://accounts.nintendo.com",
  "nintendo": "https://accounts.nintendo.com",
  "ea play": "https://myaccount.ea.com/cp-ui/aboutme/index",
  "steam": "https://store.steampowered.com/login/",
  "epic games": "https://www.epicgames.com/id/login",

  // Big tech / storage
  "amazon": "https://www.amazon.com/ap/signin",
  "icloud": "https://appleid.apple.com",
  "icloud+": "https://appleid.apple.com",
  "apple one": "https://appleid.apple.com",
  "onedrive": "https://account.microsoft.com",
  "backblaze": "https://secure.backblaze.com/user_signin.htm",

  // Education
  "duolingo": "https://www.duolingo.com/log-in",
  "duolingo plus": "https://www.duolingo.com/log-in",
  "masterclass": "https://www.masterclass.com/login",
  "skillshare": "https://www.skillshare.com/login",
  "udemy": "https://www.udemy.com/join/login-popup/",
  "coursera": "https://www.coursera.org/login",
  "pluralsight": "https://app.pluralsight.com/id/",
  "linkedin learning": "https://www.linkedin.com/login",
  "linkedin premium": "https://www.linkedin.com/login",
};

export function getCancelUrl(name: string): string | undefined {
  return CANCEL_URL_MAP[name.toLowerCase().trim()];
}
